# Change these first
owner: jyacot # Your GitHub organization or username, where this repository lives
repo: jeanlogistics-status # The name of this repository

sites:
  - name: Norson
    url: https://norson.jeanlogistics.com/
  - name: Norson - RRHH
    url: https://norson.jeanlogistics.com/rrhh/#/
  - name: Norson - Seguridad Patrimonial
    url: https://norson.jeanlogistics.com/seguridad_patrimonial
  - name: Norson -  Seguridad Industrial
    url: https://norson.jeanlogistics.com/seguridad_industrial
  - name: Bustracker - LandingPage
    url: http://www.jeanlogistics.com/bustracker/
  #- name: Dp - Tracking
  #  url: https://tracking.grupodp.com.mx/web/
  - name: Matatias
    url: https://matatias.jeanlogistics.com/web/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /jeanlogistics-status
  logoUrl: https://scontent-mia3-2.xx.fbcdn.net/v/t1.6435-9/cp0/e15/q65/p320x320/151584348_106060834859345_4498756817865479275_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=dd9801&efg=eyJpIjoidCJ9&_nc_ohc=01lK4D1tLigAX-34dJf&_nc_ht=scontent-mia3-2.xx&oh=00_AT_sqoK9syIVypeuNV33TOaLunL0whXwpFMdGJpI03H06Q&oe=621D52E6
  name: JeanLogistics
  introTitle: "Nos dedicamos a la automatización de procesos operativos de las organizaciones para que éstos fluyan en su lógica natural y evitar perdidas de tiempo y ahorro de costos."
  introMessage: Estado de nuestros Servicios
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
